import * as THREE from 'three'
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader.js'

// v2 robot model loader. Parallel to the v1 OBJ/MTL pipeline.
//
// Critical: the outer Group here is the "pivot" — it carries the Z-up→Y-up
// correction and any uniform scale. The caller parents this pivot under the
// v1 `robot_body` Object3D which is the thing the physics loop writes
// body.rotation() into every frame. If we rotated `robot_body` itself the
// rotation would be clobbered each tick; applying the correction to an inner
// pivot keeps the outer root free for the sync loop.

const BASE_URL = '/js-simulator/models/robots/v2'

const PARTS = [
  'b1_p_f', 'b2_p_f', 'b3_p_f',
  'batterycover',
  'left_fender', 'right_fender',
  'left_eye', 'right_eye',
  'lego_top',
  'pen_holder',
] as const
type PartName = typeof PARTS[number]

const WHITE = '#f2f2f0'
const NAVY = '#202aa0'
const DARK_GRAY = '#4a4a4a'
const BLACK = '#0a0a0a'

const PART_COLOR: Record<PartName, string> = {
  b1_p_f: WHITE, b2_p_f: WHITE, b3_p_f: NAVY,
  batterycover: DARK_GRAY,
  left_fender: NAVY, right_fender: NAVY,
  left_eye: WHITE, right_eye: WHITE,
  lego_top: WHITE,
  pen_holder: WHITE,
}

// ─── Per-part layout ─────────────────────────────────────────────────────────
//
// Units are STL NATIVE (millimeters, Fusion Z-up — so +Z is the robot's
// vertical, +Y is forward (after the later front/back flip), +X is the right
// side). Values are added on top of the CAD position.
//
// Tuple layout for both `pos` and `rot` is [X, Y, Z]:
//   pos — X = left(−)/right(+) mm,  Y = back(−)/front(+) mm (pre-flip),  Z = down(−)/up(+) mm
//   rot — radians about STL X / Y / Z axes (pre-axis-correction, pre-flip)
//
// PART_DEFAULTS is the baked-in baseline that always applies — values were
// dialed in manually. PART_ADJUST is an optional delta on top (summed with
// defaults) intended for a future debug menu. Empty entries in ADJUST = no
// extra offset beyond defaults.
type PartAdjust = { pos?: [number, number, number]; rot?: [number, number, number] }

const PART_DEFAULTS: Partial<Record<PartName, PartAdjust>> = {
  b1_p_f: { pos: [0, 0, 20] },
  b2_p_f: { pos: [0, 0, 20] },
  b3_p_f: { pos: [0, 0, 26] },
  batterycover: { pos: [0, 0, 21] },
  left_fender: { pos: [0, 0, 16] },
  // right_fender is auto-mirrored from left_fender (X negated, Y/Z identical)
  // unless an explicit entry exists in PART_DEFAULTS or PART_ADJUST.
  // right_fender geometry itself is regenerated by mirroring left_fender across
  // X, because the shipped right_fender.stl is broken.
  left_eye: { pos: [0, 0, 26] },
  right_eye: { pos: [0, 0, 26] },
  lego_top: { pos: [0, 0, 23] },
  pen_holder: { pos: [0, 0, 21] },
}

export const PART_ADJUST: Partial<Record<PartName, PartAdjust>> = {
  // b1_p_f:        { pos: [0, 0, 0], rot: [0, 0, 0] },
  // b2_p_f:        { pos: [0, 0, 0], rot: [0, 0, 0] },
  // b3_p_f:        { pos: [0, 0, 0], rot: [0, 0, 0] },
  // batterycover:  { pos: [0, 0, 0], rot: [0, 0, 0] },
  // left_fender:   { pos: [0, 0, 0], rot: [0, 0, 0] },
  // right_fender:  { pos: [0, 0, 0], rot: [0, 0, 0] },
  // left_eye:      { pos: [0, 0, 0], rot: [0, 0, 0] },
  // right_eye:     { pos: [0, 0, 0], rot: [0, 0, 0] },
  // lego_top:      { pos: [0, 0, 0], rot: [0, 0, 0] },
  // pen_holder:    { pos: [0, 0, 0], rot: [0, 0, 0] },
}

// Whole-pivot adjustment. Applied AFTER scale + axis correction, so units here
// are WORLD METERS in the final Y-up frame. Useful for shifting the entire
// model up/down/left/right without recomputing per-part offsets.
//
// Tuple layout [X, Y, Z] in Y-up world frame:
//   pos — X = left(−)/right(+) m,  Y = down(−)/up(+) m,  Z = forward(−)/back(+) m
//   rot — radians about world X / Y / Z, applied on top of the X=-π/2 axis correction
const PIVOT_ADJUST = {
  pos: [0, 0, 0] as [number, number, number], // world meters
  rot: [0, 0, 0] as [number, number, number], // radians
}

// Target: fender center Y = V1_WHEEL_Y so the reused v1 wheels dock into the
// v2 fenders cleanly. Change this if v2 wheels should sit at a different hub
// height than v1's 0.015 m default.
const V1_WHEEL_Y = 0.015

// ─── Wheel layout (v2 reuses v1 wheel meshes) ────────────────────────────────
//
// We keep the v1 wheel MODEL (so animate.js keeps spinning them on drive) but
// let v2 override its transform. Values are deltas applied in the robot_body
// local frame (Y-up) AFTER docking at fender centers. Detach restores the
// original v1 transform.
//
// Units are friendly — MILLIMETERS and DEGREES, not meters/radians.
//
// Tuple layout [X, Y, Z] in Y-up local frame:
//   pos   — MM delta from docked pos: X left(−)/right(+), Y down(−)/up(+), Z forward(−)/back(+)
//           (X is mirrored on the left wheel so one value moves both wheels
//            symmetrically outward/inward)
//   rot   — DEGREE delta added to the v1 wheel rotation about local X / Y / Z
//   scale — uniform multiplier on the v1 wheel scale (1 = unchanged)
//
// WHEEL_DEFAULTS is the baked-in baseline. WHEEL_ADJUST is an optional delta
// on top (pos/rot summed, scale multiplied) for a future debug menu.
export const WHEEL_DEFAULTS = {
  pos: [-24, 0, 0] as [number, number, number], // mm
  rot: [0, 0, 0] as [number, number, number], // degrees
  scale: 1,
}

export const WHEEL_ADJUST = {
  pos: [0, 0, 0] as [number, number, number], // mm
  rot: [0, 0, 0] as [number, number, number], // degrees
  scale: 1,
}

export interface RobotV2 {
  pivot: THREE.Group
  leftFenderCenter: THREE.Vector3
  rightFenderCenter: THREE.Vector3
}

const _stlLoader = new STLLoader()

function loadPart(name: PartName): Promise<THREE.Mesh> {
  return new Promise((resolve, reject) => {
    _stlLoader.load(
      `${BASE_URL}/${name}.stl`,
      (geom) => {
        geom.computeVertexNormals()
        const mat = new THREE.MeshStandardMaterial({
          color: PART_COLOR[name],
          roughness: 0.55,
          metalness: 0.05,
        })
        const mesh = new THREE.Mesh(geom, mat)
        mesh.name = `v2_${name}`
        mesh.castShadow = true
        mesh.receiveShadow = true
        mesh.userData.isRobotPart = true
        resolve(mesh)
      },
      undefined,
      (err) => reject(err),
    )
  })
}

/**
 * Return a copy of `src` mirrored across the X axis with triangle winding
 * flipped so face normals still point outward after the reflection. STLLoader
 * returns non-indexed geometry, so we operate directly on the position attribute.
 */
function mirrorGeometryX(src: THREE.BufferGeometry): THREE.BufferGeometry {
  const g = src.clone()
  g.applyMatrix4(new THREE.Matrix4().makeScale(-1, 1, 1))
  const pos = g.attributes.position.array as Float32Array
  for (let i = 0; i < pos.length; i += 9) {
    for (let c = 0; c < 3; c++) {
      const tmp = pos[i + 3 + c]
      pos[i + 3 + c] = pos[i + 6 + c]
      pos[i + 6 + c] = tmp
    }
  }
  g.attributes.position.needsUpdate = true
  g.computeVertexNormals()
  return g
}

/**
 * Load, assemble, and axis-correct the v2 model.
 *
 * @param targetWidth meters. Bottom base's X extent is scaled to this.
 */
export async function createRobotV2Pivot(targetWidth: number): Promise<RobotV2> {
  const meshes = await Promise.all(PARTS.map(p => loadPart(p)))
  const byName: Partial<Record<PartName, THREE.Mesh>> = {}
  PARTS.forEach((p, i) => { byName[p] = meshes[i] })

  // 1. Fix broken right_fender.stl — CAD export mirrored along Z (vertical)
  //    instead of X (left/right), leaving right_fender half below ground and
  //    sharing X with left_fender. Regenerate by mirroring left_fender's
  //    geometry across X.
  {
    const leftGeo = byName.left_fender!.geometry
    const mirroredGeo = mirrorGeometryX(leftGeo)
    byName.right_fender!.geometry.dispose()
    byName.right_fender!.geometry = mirroredGeo
  }

  // 2. Assemble FIRST (before any PART_ADJUST) so bbox / ground-alignment are
  //    computed on the unmodified CAD. Otherwise any adjustment on the current
  //    lowest part feeds back into `-box.min.z` below and causes the entire
  //    assembly to counter-shift — which looks like "everything moves except
  //    the part I just edited".
  const assembly = new THREE.Group()
  assembly.name = 'v2_assembly'
  meshes.forEach(m => assembly.add(m))

  // 3. Raw bbox of the UNADJUSTED assembly (STL native coords, Fusion Z-up).
  const box = new THREE.Box3().setFromObject(assembly)
  const size = new THREE.Vector3(); box.getSize(size)
  const center = new THREE.Vector3(); box.getCenter(center)

  // 4. Flip front/back. CAD faces the eye/hole side along -Y; we want them to
  //    face world -Z (forward). Rotate 180° about STL vertical (Z).
  assembly.rotation.z = Math.PI

  // 5. Recenter. Post-rotation, a child at (x, y, z) lands at (-x, -y, z), so
  //    translating by (cx, cy, -box.min.z) puts X/Y center at origin and the
  //    lowest Z at 0.
  assembly.position.set(center.x, center.y, -box.min.z)

  // 6. Autoscale: base horizontal extent → targetWidth.
  const b1Box = new THREE.Box3().setFromObject(byName.b1_p_f!)
  const b1Size = new THREE.Vector3(); b1Box.getSize(b1Size)
  const rawWidth = Math.max(b1Size.x, b1Size.y)
  const scale = targetWidth / rawWidth

  console.log(`[robotV2] bbox=${size.x.toFixed(1)}×${size.y.toFixed(1)}×${size.z.toFixed(1)} (STL units), scale=${scale.toExponential(2)}, targetWidth=${targetWidth.toFixed(3)}m`)

  // 7. Outer pivot — Z-up → Y-up axis correction + uniform scale.
  const pivot = new THREE.Group()
  pivot.name = 'v2_pivot'
  pivot.rotation.set(
    -Math.PI / 2 + PIVOT_ADJUST.rot[0],
    PIVOT_ADJUST.rot[1],
    PIVOT_ADJUST.rot[2],
  )
  pivot.scale.setScalar(scale)
  pivot.add(assembly)
  pivot.updateMatrixWorld(true)

  // 8. Vertical alignment: shift pivot so fender center Y matches v1 wheel Y.
  const leftFenderBox = new THREE.Box3().setFromObject(byName.left_fender!)
  const rightFenderBox = new THREE.Box3().setFromObject(byName.right_fender!)
  const leftFenderCenter = new THREE.Vector3(); leftFenderBox.getCenter(leftFenderCenter)
  const rightFenderCenter = new THREE.Vector3(); rightFenderBox.getCenter(rightFenderCenter)
  const fenderY = (leftFenderCenter.y + rightFenderCenter.y) / 2
  pivot.position.set(
    PIVOT_ADJUST.pos[0],
    V1_WHEEL_Y - fenderY + PIVOT_ADJUST.pos[1],
    PIVOT_ADJUST.pos[2],
  )
  pivot.updateMatrixWorld(true)

  // 9. Apply per-part offsets LAST — pure local mesh offsets that don't feed
  //    back into the ground / wheel-docking alignment above, so editing one
  //    part moves only that part. PART_DEFAULTS + PART_ADJUST are summed.
  //    If right_fender has no explicit entry, auto-mirror left_fender's
  //    combined offset (negate X, keep Y/Z) so symmetric tweaks only need
  //    one edit.
  const sum = (a?: PartAdjust, b?: PartAdjust): PartAdjust | undefined => {
    if (!a && !b) return undefined
    const pa = a?.pos, pb = b?.pos
    const ra = a?.rot, rb = b?.rot
    return {
      pos: (pa || pb) ? [(pa?.[0] ?? 0) + (pb?.[0] ?? 0), (pa?.[1] ?? 0) + (pb?.[1] ?? 0), (pa?.[2] ?? 0) + (pb?.[2] ?? 0)] : undefined,
      rot: (ra || rb) ? [(ra?.[0] ?? 0) + (rb?.[0] ?? 0), (ra?.[1] ?? 0) + (rb?.[1] ?? 0), (ra?.[2] ?? 0) + (rb?.[2] ?? 0)] : undefined,
    }
  }
  const effectiveAdjust: Partial<Record<PartName, PartAdjust>> = {}
  for (const p of PARTS) {
    const combined = sum(PART_DEFAULTS[p], PART_ADJUST[p])
    if (combined) effectiveAdjust[p] = combined
  }
  if (!effectiveAdjust.right_fender && effectiveAdjust.left_fender) {
    const src = effectiveAdjust.left_fender
    effectiveAdjust.right_fender = {
      pos: src.pos ? [-src.pos[0], src.pos[1], src.pos[2]] : undefined,
      rot: src.rot ? [src.rot[0], -src.rot[1], -src.rot[2]] : undefined,
    }
  }
  for (const p of PARTS) {
    const adj = effectiveAdjust[p]
    if (!adj) continue
    const m = byName[p]!
    if (adj.pos) m.position.set(adj.pos[0], adj.pos[1], adj.pos[2])
    if (adj.rot) m.rotation.set(adj.rot[0], adj.rot[1], adj.rot[2])
  }

  // Re-measure fender centers post-shift + adjust so the caller can dock wheels
  // at whatever the fender's actual current position is.
  pivot.updateMatrixWorld(true)
  leftFenderBox.setFromObject(byName.left_fender!)
  rightFenderBox.setFromObject(byName.right_fender!)
  leftFenderBox.getCenter(leftFenderCenter)
  rightFenderBox.getCenter(rightFenderCenter)

  return { pivot, leftFenderCenter, rightFenderCenter }
}
