title: Default
description: Current benchmark settings
stages:
  - stage_white_rect
  - stage_eiffel
  - stage_animals
  - stage_white_paper
  - stage_maze
warmupMs: 500
idleMs: 2000
moveMs: 2000
movement: 0.75
cameraMode: orbit
stageOverrides:
  - index: 0
    idleMs: 2000
    moveMs: 30000
    cameraMode: orbit
    driveMode: fixed
    movement: 1
  - index: 1
    idleMs: 2000
    moveMs: 30000
    cameraMode: orbit
    driveMode: fixed
    movement: 0.75
  - index: 2
    idleMs: 2000
    moveMs: 30000
    cameraMode: top
    driveMode: fixed
    movement: 0.75
  - index: 3
    idleMs: 500
    moveMs: 30000
    cameraMode: follow
    driveMode: lineFollower
    movement: 0.75
  - index: 4
    idleMs: 2000
    moveMs: 30000
    cameraMode: follow
    driveMode: fixed
    movement: 0.5
